### ISSUE TITLE
`source` variable importance functions

### ISSUE THREAD

**Issue by benkeser** [benkeser/slapnap#7]
@bdwilliamson -- you had some of your variable importance functions `source`d in the preamble. I've sense moved them out to avoid errors when they're not computed. Could you find the relevant place to put them back in?

**Comment by bdwilliamson** [comment]
I'm having trouble seeing in the diffs where variable importance is being compiled now (both population-level and ML-level), and which `source`d functions were moved. Can you point me to where things live now?

**Comment by benkeser** [comment]
Should be new files in /code where I copied code over from preamble.
________________________________

**Comment by bdwilliamson** [comment]
I just submitted a PR that provides some fixes. I tested report generation with both opts$importance_grp = "" and opts$importance_grp = "marg", and opts$importance_ind = "pred" and opts$importance_ind = "marg;pred". No errors on my machine!

I should also point out that if you're using results from run_super_learners created any time prior to Feb 7, you'll have to re-run run_super_learners and get_vimp -- I updated the vimp package version, and changed a bit of how the super learners are run for variable importance, so that may be what was causing you errors.

**Comment by bdwilliamson** [comment]
@benkeser where do we stand with this? Is the issue resolved on your end?

**Comment by benkeser** [comment]
Still need to check. Had just started to write scripts for unit testing, but got side-tracked this week. Hopefully can get to it early next week.

**Comment by bdwilliamson** [comment]
This issue should be fixed in #9 , but let me know if you're still running into problems!
